// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeX6ytBHZv40f-V1dFUWyvnVfC5FjAmUQ',
    appId: '1:879186491928:android:df679dc3292e6d39d2216d',
    messagingSenderId: '879186491928',
    projectId: 'chat-app-df576',
    storageBucket: 'chat-app-df576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_JDEB3YaMM50r14CVGE0R0JqImeiwCdg',
    appId: '1:879186491928:ios:8d9b82a1a2af3f1ed2216d',
    messagingSenderId: '879186491928',
    projectId: 'chat-app-df576',
    storageBucket: 'chat-app-df576.appspot.com',
    androidClientId: '879186491928-0gidk4ejjq4a2koo0vpht9odemfckt5d.apps.googleusercontent.com',
    iosClientId: '879186491928-4a15otd41icm6tsqp8argek4065rvibr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
